matrix:
  include:
    - os: linux
      language: python
      python: 3.6

install:
  - pip install .

before_script:
  - printf "[sandbox.zenodo.org]\ntoken = $ZENODO_SANDBOX_TOKEN\n[zenodo.org]\ntoken = $ZENODO_TOKEN\n" > datalight.config

script:
  - pytest tests